version: '2.3'

services:

    django:
        build: .
        init: true
        command: ./manage.py runserver 0.0.0.0:8000
        ports:
            - '80:8000'
        volumes:
            - '.:/opt/my-web-app'
        environment:
            DJANGO_SETTINGS_MODULE: 'develop.settings'
            DATABASE_URL: 'postgres://postgres@database/postgres'
        depends_on:
            - database

    database:
        image: postgres
