version: '2.3'

services:

    django:
        build:
            context: .
            target: django
        init: true
        command: ./manage.py runserver 0.0.0.0:8000
        ports:
            - '80:8000'
        volumes:
            - '.:/opt/my-web-app'
        environment:
            DJANGO_SETTINGS_MODULE: 'develop.settings'
            DATABASE_URL: 'postgres://postgres@database/postgres'
            CELERY_BROKER_URL: 'amqp://rabbitmq'
        depends_on:
            - database
            - rabbitmq

    celery:
        build:
            context: .
            target: celery
        init: true
        command: celery -A mywebapp worker -l info
        volumes:
            - '.:/opt/my-web-app'
        environment:
            DJANGO_SETTINGS_MODULE: 'develop.settings'
            DATABASE_URL: 'postgres://postgres@database/postgres'
            CELERY_BROKER_URL: 'amqp://rabbitmq'
        depends_on:
            - database
            - rabbitmq

    rabbitmq:
        image: rabbitmq

    database:
        image: postgres

    mail:
        image: djfarrelly/maildev
        ports:
            - "9000:80"
